<?php
/*
Plugin Name: Immedia - Display Lists
*/



function display_lists_function(){
		
	$blockout = "";
	$blockout .= "<div class='row list-row'>";
	//connect to database
	global $wpdb;
		$table_name = $wpdb->prefix . "tblListsDB";
		$table_name2 = $wpdb->prefix . "tblMumsDB";
        //$dlfresults = $wpdb->get_results( "SELECT * FROM wp_tblListsDB WHERE ld_list_status = 1");
		$dlfresults = $wpdb->get_results( "SELECT $table_name.*, $table_name2.* FROM $table_name INNER JOIN $table_name2 ON $table_name.ld_md_id = $table_name2.md_wp_id WHERE $table_name.ld_list_status = 1");
        foreach ( $dlfresults as $dlfblock ) {
		//print_r($dlfblock);
		$listID = $dlfblock->ld_id;

	if ($dlfblock->md_wp_id) {
	
		$scanImage = $dlfblock->md_baby_scan_image;

		$dlfprods = $wpdb->get_results( "SELECT * FROM wp_tblProductsDB WHERE pd_ld_id = $listID");
		$pd_prod_bought = 0;
		$pd_prod_total = 0;
		foreach ($dlfprods as $dprod){
			if($dprod->pd_bought == 1){
				$pd_prod_bought = $pd_prod_bought + 1;
			}
			$pd_prod_total = $pd_prod_total + 1;
		}
		if ($pd_prod_total==$pd_prod_bought) {
			$pdComplete = 1;
		} else {
			$pdComplete = 0;
		}
	
	$blockout .= "<div class='col-sm-12 col-md-6 col-lg-4'>";
			$blockout .= "<a href='/bumplist/?bump-id=".$dlfblock->ld_id."'>";
				$blockout .= "<div class='bumplistbox'>";
					$blockout .= "<div class='col-xs-8 col-sm-6 text-col'>";
						$blockout .= "<h3>". stripslashes($dlfblock->ld_list_name) ."</h3>";		
						$blockout .= "<p>From ".$dlfblock->md_firstname." ".$dlfblock->md_familyname . "</p>";
						if ($pdComplete==1)	{
							$blockout .= "<div class='list-complete'><i class='far fa-check-circle'></i> COMPLETED</div>";
						} else {
							$blockout .= "<button href='/bumplist/?bump-id=".$dlfblock->ld_id."'>View list</button>";
						}
					$blockout .= "</div>";
					
					$blockout .= "<div class='col-xs-4 col-sm-6 text-right'>";
					if($scanImage){
						$blockout .= "<img src='" . $scanImage . "' />";
					} else {
						$blockout .= "<img src='/wp-content/uploads/2021/08/list-placeholder.jpg' />";
					}
					$blockout .= "</div>";
				$blockout .= "</div>";
			$blockout .= "</a>";
	$blockout .= "</div>";
			}	
		}
	$blockout .= "</div>";
		//$blockout .= "these results are generated by the display-lists plugin";
	
	
	return $blockout;


}

function register_dlf_shortcode(){
   add_shortcode('display-lists', 'display_lists_function');
}
add_action( 'init', 'register_dlf_shortcode');
?>