<?php

/**
 /* Template Name: Our Story Template 
 *
 
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site may use a
 * different template.
 *
 * @link https://codex.wordpress.org/Template_Hierarchy
 *
 * @package immedia
 */

$siteLayout = esc_attr(get_option('site_layout'));
if ($siteLayout == 'Normal') {
	get_header();
} elseif ($siteLayout == 'Linear') {
	get_header("linear");
} else {
	get_header();
}
//get mum id from storyid?
//$mumid1 = $_GET["storyid"]
//echo $mumid1;
?>

<div id="primary" class="content-area">
	<main id="main" class="site-main" role="main">

		<?php

		include_once("wp-config.php");
		include_once("wp-includes/wp-db.php");
		global $wpdb;
		$table_name = $wpdb->prefix . "tblMumsDB";

		global $current_user;
		wp_get_current_user();
		if (is_user_logged_in()) {
			$mumid1 = $current_user->ID;
			$theResult = $wpdb->get_row("SELECT * FROM $table_name WHERE md_wp_id = '" . $mumid1 . "'");
		} elseif ($_POST["storyID"]) {
			$mumid1 = $_POST["storyID"];
			$theResult = $wpdb->get_row("SELECT * FROM $table_name WHERE md_wp_id = '" . $mumid1 . "'");
		} else {
			echo "Page not found";
		}

		//if ( is_user_logged_in() ) { 

		//echo "id ".$mumid1;

		$mumTitlefound = $theResult->md_story_title;
		$mumStoryfound = $theResult->md_story;

		$scanImage = $theResult->md_baby_scan_image;
		$babyName = $theResult->md_baby_name;
		$dueDate = $theResult->md_baby_due_date;
		$dueDate = strtotime($dueDate); 
		$dueDate = date('d/m/Y', $dueDate);

		if ($mumTitlefound) {
			//echo "<h1>".$mumTitlefound."</h1>";
			//echo $mumStoryfound;
		?>
			<div class="row">
				<!-- <div data-vc-full-width="true" data-vc-full-width-init="true" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid contain-row vc_row-no-padding half-container-cont overflow-visible" style="position: relative; left: -366.5px; box-sizing: border-box; width: 1903px;"> -->
				<div class="col-md-6 half-container">
					<div class="contain-text">
						<h1><?php echo $mumTitlefound; ?></h1>
						<p class="medium"><?php echo $mumStoryfound; ?></p>
						<div class="vc_btn3-container vc_btn3-inline">

						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="polaroid-wrapper">
						<div class="polaroid">
							<img src="<?php echo $scanImage; ?>" />
							<h4><?php echo $babyName; ?></br>
								EXPECTED ARRIVAL: <?php echo $dueDate; ?></h4>
						</div>
					</div>
				</div>
			</div>

		<?php
		} else { ?>
			
			<div class="row">
				<!-- <div data-vc-full-width="true" data-vc-full-width-init="true" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid contain-row vc_row-no-padding half-container-cont overflow-visible" style="position: relative; left: -366.5px; box-sizing: border-box; width: 1903px;"> -->
				<div class="col-md-12">
					<div class="contain-text">
						<h1>Our Story</h1>
						<p class="medium">This is your public story that anyone who views your wishlist will see.</p>

						<p>Don’t worry if you need to change any of the details, just click the ‘Edit’ button below.</p>
						
						<a href="/personal-info/#my-story">Edit</a>
					</div>
				</div>
			</div>
			
		<?php } ?>
		
		<div class="spacer-wrapper">
			<div class="visible-xs" style="height:70px"></div>
			<div class="visible-sm" style="height:70px"></div>
			<div class="visible-md" style="height:70px"></div>
			<div class="visible-lg" style="height:70px"></div>
		</div>
		
		<?php

		//} else {
		?>
		<!--<p>Please login</p>-->
		<?php
		//wp_loginout(); 
		//} 
		//
		?>
		<p class="hidden">these results are generated by the ourstory.php template</p>

	</main><!-- #main -->
</div><!-- #primary -->

<?php
//get_sidebar();
get_footer();
