<?php

/* Template Name: password-list-template
 *
 * @package immedia
 */

$siteLayout = esc_attr(get_option('site_layout'));
if ($siteLayout == 'Normal') {
    get_header();
} elseif ($siteLayout == 'Linear') {
    get_header("linear");
} else {
    get_header();
}

$action = "";
$listID = "";

$action = $_GET["action"];
//echo $action."<br />";

$listID = $_GET["listID"];
//echo $listID;

$listName = "";
$listName = $_GET["listName"];
?>

<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">

        <?php
        global $current_user;
        wp_get_current_user();
        if (is_user_logged_in()) {
            $mumid1 = $current_user->ID;
            //echo $mumid1;

            global $wpdb;

            $table_name = $wpdb->prefix . "tblListsDB";
            $retrieve_data = $wpdb->get_row("SELECT ld_list_name, ld_password, ld_is_protected FROM $table_name WHERE ld_id = '" . $listID . "'");
            $listName = stripslashes($retrieve_data->ld_list_name);
            $listPassword = stripslashes($retrieve_data->ld_password);
            $listProtected = stripslashes($retrieve_data->ld_is_protected);

            // we need to add 'stripslashes' in the fields below, or else if there is an apostrophe in the name, we get backslashes in the inserted value
        ?>

            <form action="" method="POST" class="update-form">
                <h2>Set Password</h2>
                <p>Set a password below. Please use a minumum of 8 characters and a maximum of 12 characters.</p>
                <input type="password" minlength="8" maxlength="12" id="listPassword" name="listPassword" value="<?php echo stripslashes($listPassword); ?>">
                <label for="listProtected">Tick below to make list private.</label>
                <input type="checkbox" id="listProtected" name="listProtected" value="1" <?php if ($listProtected == 1) {
                                                                                                echo "checked";
                                                                                            } ?>>
                <div class="update-wrap">
                    <input type="submit" value="Submit" name="form_submit">
                </div>

                <p>Private list:<br />
                    This list can only be viewed with the protected password.<br />
                    Public List: <br />
                    This list will not be password protected and will appear on search engines.
                </p>
            </form>
            <br />
            &nbsp;
        <?php
            // Don't run the query unless the form has been submitted
            if (isset($_POST["form_submit"])) {

                $tablename = $wpdb->prefix . 'tblListsDB';
                $wpdb->update(
                    $tablename,
                    array(
                        'ld_password' => $_POST['listPassword'],
                        'ld_is_protected' => $_POST['listProtected'],
                    ),
                    array(
                        'ld_id' => $listID, // the first WHERE argument
                        //'column2' => 'value2', // additional WHERE argument!
                    ),
                    array('%s', '%d'), // the format of the update value
                    array(
                        '%d', // the format of the first WHERE argument
                        //'%s' // the format of the second WHERE argument
                    )
                );

                // Redirect back to page after update
                header("Location: /edit-your-list/?listID=$listID&listName=$listName");
                exit();
            }
        }

        //echo "This page is generated by the password-list-template";
        ?>
    <p class="hidden">content generated by password-list-template.php</p>
    </main><!-- #main -->

</div><!-- #primary -->

<?php

//get_sidebar();

get_footer();
