<?php

/**
 /* Template Name: Request Deletion Template 
 *
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site may use a
 * different template.
 *
 * @link https://codex.wordpress.org/Template_Hierarchy
 *
 * @package immedia
 */

//this script takes the 'gifted' form submission and does four things:
//1) marks product as gifted on the database
//2) sends email to list owner
//3) sends thank you email to gift giver
//4) returns gift giver to the list page 

//still need to add some security.  check where it came from
// If this file is called directly, bail out!

// get the core wp functionality using shortinit
define('SHORTINIT', true);
$path = $_SERVER['DOCUMENT_ROOT'];
include_once $path . '/wp-config.php';
include_once $path . '/wp-includes/wp-db.php';
include_once $path . '/wp-includes/pluggable.php';
include_once $path . '/wp-load.php';
global $wpdb;

$siteLayout = esc_attr(get_option('site_layout'));
if ($siteLayout == 'Normal') {
    get_header();
} elseif ($siteLayout == 'Linear') {
    get_header("linear");
} else {
    get_header();
}

global $current_user;
wp_get_current_user();

$timeSubmitted = '';
$timeIsNow = '';
?>
<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
        <?php
        if (is_user_logged_in()) {
            // Get the user ID
            $mumid1 = $current_user->ID;
            global $wpdb;

            // The form below will start a new list
        ?>
            <h2>Request Account Deletion</h2>

            <h3>Please give a reason why you wish to delete this account</h3>

            <form class="create-list" action="" method="POST">
                <label for="deletionReason">Reason for deletion</label>
                <input type="text" id="deletionReason" name="deletionReason" value="" required="required">
                <input type="submit" value="Request deletion" name="form_submit">
            </form>

            <?php
            // Don't run the insert query below unless the form has been submitted
            if (isset($_POST["form_submit"])) {

                //echo "email stuff here";
                $deletionReason = $_POST['deletionReason'];
                $mum = $wpdb->get_row("SELECT * FROM wp_tblMumsDB WHERE md_wp_id = $mumid1");
                //$mumsemail = $mum->md_wp_username;
                $mumsemail = $mum->md_email;
                $mumsfirstname = $mum->md_firstname;
                $mumsfamilyname = $mum->md_familyname;

                //send an email to list owner
                //$to = $mumsemail;
                //$to = "webmaster@immedia-creative.com";
                //$to = "malcolm.kinross@immedia-creative.com";
                $to = get_bloginfo('admin_email');
                $subject = 'Account deletion request';
                $message .= '<p>The User: ';
                $message .= $mumsfirstname . " " . $mumsfamilyname;
                $message .= '<br />Has sent an account deletion request<br />Reason for deletion: ';
                $message .= $deletionReason . '</p>';
                $message .= '<p>Users Email address: ' . $mumsemail . '</p>';

                wp_mail($to, $subject, $message);

                // Redirect to profile page
            ?>
                <script type="text/javascript">
                    alert("Your deletion request has been sent");
                    document.location = "/personal-info/";
                </script>
        <?php
                exit();
            }
        }
        //echo "This page is generated by request-deletion.php";
        ?>
    </main><!-- #main -->
</div><!-- #primary -->
<?php
//get_sidebar();
get_footer();
