<?php

 /* Template Name: update-wp-user-template
 *
 * @package immedia
 */

$siteLayout = esc_attr( get_option( 'site_layout' ) );
if($siteLayout == 'Normal'){
get_header();
}

elseif($siteLayout == 'Linear'){
get_header("linear");
}

else{
get_header();
}

//$fieldname = get_query_var('fieldname');
$fieldname = $_GET["fieldname"];
//echo $fieldname;

//$action = "";
//$email = "";
//$password = "";
//$action = $_GET["action"];
//$email = $_GET["email"];
//$password = $_GET["password"];

global $current_user; wp_get_current_user();
?>

<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">

    <?php
    if ( is_user_logged_in() ) {
        $mumid1 = $current_user->ID;
        include_once("wp-includes/user.php");

        global $wpdb;

        if ($fieldname!="md_password") {
            $table_name = $wpdb->prefix . "tblMumsDB";
            // this will get the data from your table
            $retrieve_data = $wpdb->get_results( "SELECT $fieldname FROM $table_name WHERE md_wp_id = '".$mumid1."'" );
            
            foreach ($retrieve_data as $retrieved_data){
                $resultFromDB = $retrieved_data->$fieldname;
            }
        }
        //echo $resultFromDB;
        ?>
        
        <div id="primary" class="content-area">
    	<main id="main" class="site-main" role="main">
    	
    	<form action="" method="POST" class="update-form">
    	    
    	<?php
        switch ($fieldname) {
            case "md_password":
                ?>
                <label for="password">new password</label>
    		    <input type="password" id="password" name="postedvalue" value="">
    		    <?php
                break;
            case "md_email":
                ?>
                <label for="email">Email</label>
    		    <input type="text" id="email" name="postedvalue" value="<?php echo $resultFromDB; ?>">
    		    <?php
                break;
            default:
                echo "No field specified";
        }
    	?>		<div class="update-wrap">		<a class="cancel-update" href="/personal-info/">Cancel</a>
    	<input type="submit" value="Update" name="form_submit">		</div>
    	</form>

        <?php
        if(isset($_POST["form_submit"])) {

            if($fieldname=="md_email") {
                // echo "email section<br />";
                // check if user is really updating the value
                if ($user_email != $_POST['postedvalue']) {       
                    // check if email is free to use
                    if (email_exists( $_POST['postedvalue'] )){
                        // Email exists, do not update value.
                        // Maybe output a warning.
                        echo "This email is already in use. Please choose another email address.<br />";
                    } else {
                        $args = array(
                            'ID'         => $mumid1,
                            'user_email' => esc_attr( $_POST['postedvalue'] )
                        );            
                        wp_update_user( $args );

                        $postedvalue = $_POST['postedvalue'];

                        $tablename = $wpdb->prefix.'tblMumsDB';
                        $wpdb->update( $tablename, array(
                            $fieldname => $postedvalue,
                            ),
                            array(
                            'md_wp_id' => $mumid1,
                            ),
                            array('%s'),
                            array(
                            '%d',
                            )
                        );
                        
                        // Redirect back to profile page after update
                        header("Location: /personal-info/");
                        //echo "update user db<br />";
                        //echo $_POST['postedvalue'];
                        exit();
                    }   
                }

            } elseif ($fieldname=="md_password") {
                //echo "password section<br />";

                $user_id = $mumid1;
                $password = $_POST['postedvalue'];
                wp_set_password( $password, $user_id );

                // Redirect back to profile page after update
                header("Location: /personal-info/");

                //echo "update user db<br />";
                //echo $password;
                exit();

            } else {
                echo "No fieldname set";
            }
        }
    }
    //echo "This page is generated by the update-wp-user-template";
    ?>

    </main><!-- #main -->

</div><!-- #primary -->

<?php

//get_sidebar();

get_footer();