<?php

 /* Template Name: update-list-template
 *
 * @package immedia
 */

$siteLayout = esc_attr( get_option( 'site_layout' ) );
if($siteLayout == 'Normal'){
get_header();
}

elseif($siteLayout == 'Linear'){
get_header("linear");
}

else{
get_header();
}

$action = "";
$listID = "";

$action = $_GET["action"];
//echo $action."<br />";

$listID = $_GET["listID"];
//echo $listID;

$listName = "";
$listName = $_GET["listName"];
?>

<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">

    <?php
    global $current_user; wp_get_current_user();
    if ( is_user_logged_in() ) {
        $mumid1 = $current_user->ID;
        //echo $mumid1;

        global $wpdb;

        if ($action == "update"){

            $table_name = $wpdb->prefix . "tblListsDB";
            $retrieve_data = $wpdb->get_row( "SELECT ld_list_name FROM $table_name WHERE ld_id = '".$listID."'" );
            $listName = stripslashes($retrieve_data->ld_list_name);

            // we need to add 'stripslashes' in the fields below, or else if there is an apostrophe in the name, we get backslashes in the inserted value
            ?>

            <form action="" method="POST" class="update-form">
			<h2>Edit List Name</h2>
            <input type="text" id="listName" name="listName" value="<?php echo stripslashes($listName); ?>" required>
			<div class="update-wrap">
			<input type="submit" value="Submit" name="form_submit">
			</div>
			
            </form>
            <br />
            &nbsp;
            <?php
            // Don't run the query unless the form has been submitted
            if(isset($_POST["form_submit"])) {

                $tablename = $wpdb->prefix.'tblListsDB';
                $wpdb->update( $tablename, array(
                    'ld_list_name' => $_POST['listName'],
                    ),
                    array(
                    'ld_id' => $listID, // the first WHERE argument
                    //'column2' => 'value2', // additional WHERE argument!
                    ),
                    array('%s'), // the format of the update value
                    array(
                    '%d', // the format of the first WHERE argument
                    //'%s' // the format of the second WHERE argument
                    )
                );

                // Redirect back to page after update
                header("Location: /edit-your-list/?listID=$listID&listName=$listName");
                exit();
                }

            } elseif ($action == "delete") {

                // Check to see if there are any products still in the list
                $dlfprods = $wpdb->get_results( "SELECT * FROM wp_tblProductsDB WHERE pd_ld_id = $listID");
                $pd_prod_total = 0;
                foreach ($dlfprods as $dprod){
                    $pd_prod_total = $pd_prod_total + 1;
                }
                if ($pd_prod_total > 0){
                    //return to page
                    //echo "prod total = ".$pd_prod_total;
                    echo "You still have products associated with this list. Please go back to your list page to delete them <a href='edit-your-list/?listID=".$listID."&listName=".$listName."'>Back</a>";
                } else {

                $table_name = $wpdb->prefix . "tblListsDB";
                $wpdb->query(
                    "DELETE  FROM $table_name WHERE ld_id = '".$listID."'"
                );

                // Redirect back to profile page after update
                header("Location: /member-account/");
                exit();
                }
            } else {

                echo "dunno";

            }
        }

        //echo "This page is generated by the update-list-template";
        ?>
    <p class="hidden">content generated by update-list-template.php</p>
    </main><!-- #main -->

</div><!-- #primary -->

<?php

//get_sidebar();

get_footer();